---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chrome.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: chrome
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.chrome.service.type }}
  ports:
  - port: 5900
    targetPort: 5900
    {{ if eq .Values.chrome.service.type "NodePort" }}nodePort: {{ .Values.chrome.service.nodePort }}{{ end }}
  selector:
    app: chrome
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chrome.deploymentName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: chrome
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: chrome
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- toYaml .Values.chrome.rollingUpdate | nindent 6 }}
  replicas: {{ .Values.chrome.replicaCount }}
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
      - name: node-chrome
        image: {{ .Values.chrome.repository }}
        imagePullPolicy: {{ .Values.chrome.pullPolicy }}
        env:
        - name: HUB_PORT_4444_TCP_ADDR
          value: {{ .Values.hub.serviceName }}
        - name: HUB_PORT_4444_TCP_PORT
          value: "4444"
        ports:
        - containerPort: 5900
        resources:
          {{- toYaml .Values.chrome.resources | nindent 10 }}
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
