---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.firefox.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: firefox
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.firefox.service.type }}
  ports:
  - port: 5900
    targetPort: 5900
    {{ if eq .Values.firefox.service.type "NodePort" }}nodePort: {{ .Values.firefox.service.nodePort }}{{ end }}
  selector:
    app: firefox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.firefox.deploymentName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: firefox
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: firefox
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- toYaml .Values.firefox.rollingUpdate | nindent 6 }}
  replicas: {{ .Values.firefox.replicaCount }}
  template:
    metadata:
      labels:
        app: firefox
    spec:
      containers:
      - name: node-firefox
        image: {{ .Values.firefox.repository }}
        imagePullPolicy: {{ .Values.firefox.pullPolicy }}
        env:
        - name: HUB_PORT_4444_TCP_ADDR
          value: {{ .Values.hub.serviceName }}
        - name: HUB_PORT_4444_TCP_PORT
          value: "4444"
        ports:
        - containerPort: 5900
        resources:
          {{- toYaml .Values.firefox.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory