---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hub.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: selenium-hub
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.hub.service.type }}
  ports:
  - port: 4444
    targetPort: 4444
    {{ if eq .Values.hub.service.type "NodePort" }}nodePort: {{ .Values.hub.service.nodePort }}{{ end }}
  selector:
    app: selenium-hub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hub.deploymentName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: selenium-hub
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: selenium-hub
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- toYaml .Values.hub.rollingUpdate | nindent 6 }}
  replicas: {{ .Values.hub.replicaCount }}
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: {{ .Values.hub.repository }}
        imagePullPolicy: {{ .Values.hub.pullPolicy }}
        env:
        - name: GRID_BROWSER_TIMEOUT
          value: {{ .Values.hub.environmentVariables.gridBrowserTimeout | quote }}
        - name: GRID_TIMEOUT
          value: {{ .Values.hub.environmentVariables.gridTimeout | quote }}
        ports:
        - containerPort: 4444
        resources:
          {{- toYaml .Values.hub.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
