apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prometheus-datasource
data:
  prometheus.yaml: |-
    # config file version
    apiVersion: 1

    # list of datasources to insert/update depending
    # what's available in the database
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus:9090
      version: 1
      editable: true