apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeExporter.serviceName }}
  namespace: {{ .Values.nodeExporter.namespace }}
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: {{ .Values.nodeExporter.appLabel }}
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "NodeExporter"
spec:
  ports:
  - name: metrics
    port: 9200
    targetPort: 9200
  selector:
    app: {{ .Values.nodeExporter.appLabel }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.nodeExporter.daemonSetName }}
  namespace: {{ .Values.nodeExporter.namespace }}
  labels:
    app: {{ .Values.nodeExporter.appLabel }}
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      app: {{ .Values.nodeExporter.appLabel }}
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: {{ .Values.nodeExporter.appLabel }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      priorityClassName: system-node-critical
      containers:
      - name: prometheus-node-exporter
        image: {{ .Values.nodeExporter.repository }}
        imagePullPolicy: {{ .Values.nodeExporter.pullPolicy }}
        args:
          - "--web.listen-address=0.0.0.0:9200"
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
        ports:
        - name: metrics
          containerPort: 9200
          hostPort: 9200
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly:  true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        resources:
          {{- toYaml .Values.nodeExporter.resources | nindent 10 }}
      hostNetwork: true
      hostPID: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys