apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.prometheus.appLabel }}
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
      - targets: ['{{ .Values.prometheus.serviceName }}:9090']

    - job_name: 'kube-state-metrics'
      static_configs:
      - targets: ['{{ .Values.kubeStateMetrics.serviceName }}.{{ .Values.kubeStateMetrics.namespace }}:8080']
    
    - job_name: node
      static_configs:
      - targets: ['{{ .Values.nodeExporter.serviceName }}.{{ .Values.nodeExporter.namespace }}:9200']

    - job_name: postgres-exporter
      static_configs:
        - targets: ['{{ .Values.postgresExporter.serviceName }}.{{ .Values.postgresExporter.namespace }}:9187']

    - job_name: 'kubernetes-cadvisor'
      scheme: https

      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: node

      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}:10250/proxy/metrics/cadvisor