apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.provisioning.datasource.configMapDataSourceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.grafana.appLabel }}
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: {{ .Values.grafana.provisioning.datasource.prometheusUrl }}
      version: 1
      editable: true