apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.security.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.grafana.appLabel }}
    appVersion: {{ .Chart.AppVersion | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
type: Opaque
data:
  username: {{ required "A valid .Values.grafana.secret.username entry required!" .Values.grafana.security.secret.username | b64enc | quote }}
  password: {{ required "A valid .Values.grafana.secret.password entry required!" .Values.grafana.security.secret.password | b64enc | quote }}