apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - protocol: TCP
    name: web
    nodePort: 32000
    port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  serviceName: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command: ["sh", "-c", "chmod -R 777 /prometheus"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: prometheus-volume
          mountPath: /prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.10.0
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 600m
            memory: 1000Mi
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: prometheus-volume
          mountPath: /prometheus
        - name: prometheus-config
          mountPath: /etc/prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus
  volumeClaimTemplates:
  - metadata:
      name: prometheus-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp2
      resources:
        requests:
          storage: 10Gi