# Default values for Prometheus and its additional metric scrapers (kube-state-metrics, node-exporter).

prometheus:
  serviceName: prometheus
  service:
    type: NodePort
    nodePort: 32000
  statefulSetName: prometheus
  appLabel: prometheus
  repository: prom/prometheus:v2.33.5
  pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 600m
      memory: 1000Mi
  configMapName: prometheus
  rbac:
    serviceAccountName: prometheus
    clusterRole: prometheus
    clusterRoleBinding: prometheus
  basicAuth:
    enabled: true
    configMapName: prometheus-basic-auth
    password: $2a$12$5oelBjrYQ.WKIbURUryaTOBZNk6ymgbGWRGVQvN.0RYThT97rmxA. # change this password with bcrypt hash value of your choice
  enableFeature:
    remoteWriteReceiver: true
  persistence:
    #enabled: "true" # Comment this line if you don't care about the persistence
    volumeName: prometheus-volume
    storageClassName: gp2
    accessModes:
    - ReadWriteOnce
    requestStorage: 10Gi
  ingress:
    enabled: "false" # if true, prometheus will be exposed to the outside by using ingress
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: prometheus.example.com
        paths:
          - "/"
    tls:
    - secretName: tls-prometheus
      hosts:
        - prometheus.example.com

nodeExporter:
  namespace: kube-system
  serviceName: node-exporter
  daemonSetName: node-exporter
  appLabel: node-exporter
  repository: prom/node-exporter:v1.0.1
  pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 10m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 50Mi

kubeStateMetrics:
  namespace: kube-system
  rbac:
    serviceAccountName: kube-state-metrics
    clusterRole: kube-state-metrics
    clusterRoleBinding: kube-state-metrics
  serviceName: kube-state-metrics
  deploymentName: kube-state-metrics
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  appLabel: kube-state-metrics
  repository: quay.io/coreos/kube-state-metrics:v1.9.7
  pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 200Mi

postgresExporter:
  enabled: false
  namespace: prometheus-grafana # or any namespace
  serviceName: psql-metrics
  deploymentName: psql-metrics
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  appLabel: psql-metrics
  repository: prometheuscommunity/postgres-exporter:v0.10.0 # v0.10.0 used since in later versions PG_EXPORTER_EXCLUDE_DATABASES does not work properly
  pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 200Mi
  env:
    DATA_SOURCE_NAME: "postgresql://postgres:postgrespassword@postgres:5432/database?sslmode=require" # should be modified with you psql data
